### ISSUE TITLE
is support  ktor_version=2.0.3？

### ISSUE THREAD

**Issue by 287138531** [T-Fowl/ktor-jsoup#112]
install(JsoupPlugin) 

Type mismatch: inferred type is JsoupPlugin.Feature but Plugin<TypeVariable(P), TypeVariable(B), TypeVariable(F)> was expected

**Comment by T-Fowl** [comment]
Apologies for never getting around to this issue. I am in the process of giving this library some tlc and updating it so I will close this issue as stale but feel free to open another issue if you have problems in the future.
