### ISSUE TITLE
Cannot build project with dependency on ktor-jsoup 1.4.1

### ISSUE THREAD

**Issue by antonDigitalMagic** [T-Fowl/ktor-jsoup#22]
Project build fails with the following error:

![Screenshot from 2021-05-04 15-50-08](https://user-images.githubusercontent.com/69001436/117006393-0c656700-acf1-11eb-9102-cbdd2314dbb5.png)

Looks like bintray has been closed, therefore migration is needed.

**Comment by T-Fowl** [comment]
Thank you for bringing this to my attention, I thought I had more time to deal with migrating from bintray.

I have migrated to publishing to maven central, 1.4.1 should be on there now (though not showing up on search.maven.org just yet)
